apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: flowers-gateway
spec:
  gatewayClassName: envoy
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flowers-routes
spec:
  parentRefs:
  - name: flowers-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /billing
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
    backendRefs:
    - name: billing-service
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /delivery
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
    backendRefs:
    - name: delivery-service
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /order
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
    backendRefs:
    - name: order-service
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /product
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
    backendRefs:
    - name: product-service
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /user
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
    backendRefs:
    - name: user-service
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /warehouse
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
    backendRefs:
    - name: warehouse-service
      port: 8080